#!/bin/bash 
i=100
t=116
while ((i<t))
do
mkdir "R${i}"
$((i++))
done

c=200
d=216
while ((c<d))
do
mkdir "R${c}"
$((c++))
done


e=21
f=26
while ((e<f))
do
mkdir "SAE${e}"
$((e++))
done

a=11
b=16
while ((a<b))
do
mkdir "SAE${a}"
$((a++))
done